name: app_luyen_de_thpt
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3 
  firebase_core: ^3.8.0 
  firebase_storage: ^12.3.6 
  cloud_firestore: ^5.5.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  ionicons: ^0.2.2
  nb_utils: ^7.0.4
  image_picker: ^1.0.7
  http: ^1.2.2
  video_player: ^2.9.2
  crypto: ^3.0.6
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  file_picker: ^8.1.4
  permission_handler: ^11.3.1
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  flutter_localization: ^0.2.3
  flutter_math_fork: ^0.7.2
  math_keyboard: ^0.3.1
  flutter_tex: ^4.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/subject/
    - .env  